name: 'License Approval'
description: 'Check if any license in use require approval'
inputs:
  package_manager:
    description: 'Which package manager to check'
    required: true
    default: 'bundler'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.package_manager }}
branding:
  icon: 'file-text'  
  color: 'purple'
  
