name: 'License Approval'
description: 'Check if any license in use require approval'
outputs:
  license_report_json:
    description: "A report about licenses in JSON"
inputs:
  package_manager:
    description: 'Which package manager to check (comma separated)'
    required: true
    default: 'bundler'
  working_directory:
    default: '/'
    description: "Which directory to check"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package_manager }}
    - ${{ inputs.working_directory }}
branding:
  icon: 'file-text'
  color: 'purple'
