name: 'License Approval'
description: 'Check if any license in use require approval'
outputs:
  license_report_json:
    description: "A report about licenses in JSON"
runs:
  using: 'docker'
  image: 'Dockerfile'
