name: 'License Approval'
description: 'Check if any license in use requires approval'
inputs:
  working_directory:
    description: "Which directory to check"
    required: false
    default: '/'
  license_finder_version:
    description: "The version of license_finder to install"
    required: false
    default: '7.1.0'
  extra_flags:
    description: 'Additional command line flags and arguments to pass to license_finder'
    required: false
    default: ''
  ruby_version:
    description: 'The version of Ruby to use'
    required: false
    default: 'ruby-3.2'
runs:
  using: 'composite'
  steps:
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
    - name: Install license_finder
      shell: sh
      run: gem install license_finder --version ${{ inputs.license_finder_version }}
    - name: Check licenses
      working-directory: ${{ inputs.working_directory }}
      shell: sh
      run: license_finder ${{ inputs.extra_flags }}
branding:
  icon: 'file-text'
  color: 'purple'

