on:
  push:
    paths: 
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'doc/dependency_decisions.yml'

jobs:
  license_check:
    runs-on: ubuntu-latest
    name: Check for unapproved licenses
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Perform checks
      id: license-check
      uses: ralexander-phi/license_approval@testing
      with:
        package_manager: 'bundler'

